import re

def contection_to_normale(text):
    text = re.sub(r'\bal I\'m\b', 'I am', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal i\'m\b', 'I am', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal you\'re\b', 'you are', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal you\'re\b', 'you are', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal he\'s\b', 'he is', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal she\'s\b', 'she is', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal it\'s\b', 'it is', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal we\'re\b', 'we are', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal they\'re\b', 'they are', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal I\'ve\b', 'I have', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal you\'ve\b', 'you have', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal we\'ve\b', 'we have', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal they\'ve\b', 'they have', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal I\'ll\b', 'I will', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal you\'ll\b', 'you will', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal he\'ll\b', 'he will', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal she\'ll\b', 'she will', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal it\'ll\b', 'it will', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal we\'ll\b', 'we will', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal they\'ll\b', 'they will', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal I\'d\b', 'I would', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal you\'d\b', 'you would', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal he\'d\b', 'he would', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal she\'d\b', 'she would', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal it\'d\b', 'it would', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal we\'d\b', 'we would', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal they\'d\b', 'they would', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal can\'t\b', 'can not', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal don\'t\b', 'do not', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal doesn\'t\b', 'does not', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal didn\'t\b', 'did not', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal won\'t\b', 'will not', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal wouldn\'t\b', 'would not', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal isn\'t\b', 'is not', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal aren\'t\b', 'are not', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal wasn\'t\b', 'was not', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal weren\'t\b', 'were not', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal hasn\'t\b', 'has not', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal haven\'t\b', 'have not', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal hadn\'t\b', 'had not', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal isn\'t\b', 'is not', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal aren\'t\b', 'are not', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal wasn\'t\b', 'was not', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal weren\'t\b', 'were not', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal hasn\'t\b', 'has not', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal haven\'t\b', 'have not', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal hadn\'t\b', 'had not', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal isn\'t\b', 'is not', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal aren\'t\b', 'are not', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal wasn\'t\b', 'was not', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal weren\'t\b', 'were not', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal hasn\'t\b', 'has not', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal haven\'t\b', 'have not', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal hadn\'t\b', 'had not', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal isn\'t\b', 'is not', text, flags=re.IGNORECASE)
    text = re.sub(r'\bal aren\'t\b', 'are not', text, flags=re.IGNORECASE)
    text = re.sub(r'\b(I|You|He|She|It|We|They|That|This|There|Here|What|Who|Where|When|Why|How)\'ll', 'will', text, flags=re.IGNORECASE)
    text = re.sub(r'\b(I|You|He|She|It|We|They|That|This|There|Here|What|Who|Where|When|Why|How)\'re', 'are', text, flags=re.IGNORECASE)
    text = re.sub(r'\b(I|You|He|She|It|We|They|That|This|There|Here|What|Who|Where|When|Why|How)\'ye', 'have', text, flags=re.IGNORECASE)
    text = re.sub(r'\b(I|You|He|She|It|We|They|That|This|There|Here|What|Who|Where|When|Why|How)\'d', 'had', text, flags=re.IGNORECASE)
    text = re.sub(r'\b(I|You|He|She|It|We|They|That|This|There|Here|What|Who|Where|When|Why|How)\'s', 'is', text, flags=re.IGNORECASE)
    text = re.sub(r'\b(I|You|He|She|It|We|They|That|This|There|Here|What|Who|Where|When|Why|How)\'m', 'am', text, flags=re.IGNORECASE)
    text = re.sub(r'\b(I|You|He|She|It|We|They|That|This|There|Here|What|Who|Where|When|Why|How)\'ll not', 'will not', text, flags=re.IGNORECASE)
    text = re.sub(r'\b(I|You|He|She|It|We|They|That|This|There|Here|What|Who|Where|When|Why|How)\'n', 'not', text, flags=re.IGNORECASE)
    text = re.sub(r'\b(i|you|he|she|it|we|they|that|this|there|here|what|who|where|when|why|how)\'ll', 'will', text, flags=re.IGNORECASE)
    text = re.sub(r'\b(i|you|he|she|it|we|they|that|this|there|here|what|who|where|when|why|how)\'re', 'are', text, flags=re.IGNORECASE)
    text = re.sub(r'\b(i|you|he|she|it|we|they|that|this|there|here|what|who|where|when|why|how)\'ve', 'have', text, flags=re.IGNORECASE)
    text = re.sub(r'\b(i|you|he|she|it|we|they|that|this|there|here|what|who|where|when|why|how)\'d', 'had', text, flags=re.IGNORECASE)
    text = re.sub(r'\b(i|you|he|she|it|we|they|that|this|there|here|what|who|where|when|why|how)\'s', 'is', text, flags=re.IGNORECASE)
    text = re.sub(r'\b(i|you|he|she|it|we|they|that|this|there|here|what|who|where|when|why|how)\'m', 'am', text, flags=re.IGNORECASE)
    text = re.sub(r'\b(i|you|he|she|it|we|they|that|this|there|here|what|who|where|when|why|how)\'ll not', 'will not', text, flags=re.IGNORECASE)
    text = re.sub(r'\b(i|you|he|she|it|we|they|that|this|there|here|what|who|where|when|why|how)\'n', 'not', text, flags=re.IGNORECASE)
    text = re.sub(r'\b\w*\'ll', 'will', text, flags=re.IGNORECASE)
    text = re.sub(r'\b\w*\'s', 'will', text, flags=re.IGNORECASE)


    return text